### PR TITLE
Added openai API key placeholder

### PR DESCRIPTION
**Pull request by pors**

### CODE REVIEW

**Review by msoedov — APPROVED** [review]
Thx for submitting this PR! I appreciate it!

**Comment by pors** [comment]
This project has a lot of potential. What do you think of adding websockets support for chat? You can borrow ideas here: https://github.com/hwchase17/chat-langchain

If you want, I can contribute with React clients to work with the examples so users have both a backend and frontend solution that works out of the box. I haven't found anything like that around yet.

**Comment by msoedov** [comment]
Hi @pors, that's an interesting idea! Thx for the suggestion. Let me think what would be the best way to integrate it and support the persistence of one of the prompt input params like `chat_history = []` in that ws example.

**Comment by pors** [comment]
Cool!

I think in that implementation, the client keeps track of the history and sends it over every request?

This may help? https://python.langchain.com/en/latest/getting_started/getting_started.html#id1

**Comment by pors** [comment]
> I think in that implementation, the client keeps track of the history and sends it over every request?

Ignore that, the JS client I looked as sent the history over for some reason, but it should be tracked by the server (langchain memory).

**Pull request merged**
